version: '3.4'

networks:
  diegonpp:
    driver: bridge

services:
  apiprevisaotempo:
    image: ${DOCKER_REGISTRY-}apiprevisaotempo
    ports:
      - "5003:80"
    build:
      context: .
      dockerfile: PrevisaoTempo/Dockerfile
    networks:
      - diegonpp



  flurlpolly:
    image: ${DOCKER_REGISTRY-}flurlpolly
    ports:
      - "5004:80"
    build:
      context: .
      dockerfile: FlurlPolly/Dockerfile
    networks:
      - diegonpp
